# Generated by Django 4.1.4 on 2023-02-01 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_job_translator_alter_job_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='translated_text',
            field=models.TextField(blank=True),
        ),
    ]
