# Generated by Django 4.1.4 on 2023-02-02 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_job_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='rating',
        ),
    ]
