# Generated by Django 4.1.4 on 2023-02-02 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('STATE_NOT_ASSIGNED', 'Not assigned'), ('STATE_IN_PROGRESS', 'In Progress'), ('STATE_COMPLETED', 'Completed')], default='STATE_NOT_ASSIGNED', max_length=20),
        ),
    ]
