# Generated by Django 4.1.4 on 2023-02-02 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0011_biddingoffer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biddingoffer',
            name='translator',
            field=models.ForeignKey(limit_choices_to={'is_translator': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
