# Generated by Django 4.1.4 on 2023-02-04 06:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0013_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='translator',
            field=models.ForeignKey(blank=True, default=1, limit_choices_to={'is_translator': True}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='translator', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
