# Generated by Django 4.1.4 on 2023-02-04 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0014_alter_job_translator_alter_rating_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='translator',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_translator': True}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='translator', to=settings.AUTH_USER_MODEL),
        ),
    ]
