# Generated by Django 4.1.4 on 2023-02-04 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_job_translator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='translated_text',
            field=models.TextField(),
        ),
    ]
