# Generated by Django 4.1.4 on 2023-02-04 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_job_translated_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='translated_text',
            field=models.TextField(blank=True),
        ),
    ]
